title: Lone Journal
author: Akzolon
subtitle: A Voyage Through The Unknown

url: "https://akzolon.github.io"
baseurl: "/Journal"

footer_only_homepage: true
footer_url: "https://github.com/Akzolon"
footer_text: "Visit my Github"

profile-picture: assets/profile.png
favicon_location: assets/favicon.ico

permalink: /:year-:month-:day-:title/
sass:
    style: compressed
    sass_dir: css

navbar:
 - name: "About"
   link: "about"
 - name: "Portfolio"
   absolute-link: "https://www.youtube.com/watch?v=5aQ6QMvharg"
